export const keywords = [
    { id: 2, keyword: "React JS" },
    { id: 3, keyword: "Funny Cat" },
    { id: 4, keyword: "Cute Babies" },
    { id: 5, keyword: "iPhone 13" },
    { id: 6, keyword: "Minimalism" },
    { id: 7, keyword: "COVID News" },
    { id: 8, keyword: "Nature sounds" },
    { id: 9, keyword: "Art" },
    { id: 10, keyword: "Culinary" },
    { id: 11, keyword: "ASMR" },
    { id: 12, keyword: "Motivation" },
    { id: 13, keyword: "Islam" },
    { id: 14, keyword: "Mr Bean" },
    { id: 15, keyword: "Gadgets" },
];
