export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const POPULAR_VIDEOS_SUCCESS = "POPULAR_VIDEOS_SUCCESS";
export const POPULAR_VIDEOS_FAILED = "POPULAR_VIDEOS_FAILED";
export const POPULAR_VIDEOS_REQUEST = "POPULAR_VIDEOS_REQUEST";
